"""PaperBanana-inspired diagram support for final MiroFish reports."""

from __future__ import annotations

import re
from dataclasses import asdict, dataclass
from typing import Any


MIN_REPORT_DIAGRAMS = 3
DIAGRAM_SECTION_TITLE = "Diagramas PaperBanana"
DIAGRAM_GENERATOR = "mirofish.paperbanana_diagrams"
DIAGRAM_GENERATOR_VERSION = "1.0"

_MERMAID_FENCE_RE = re.compile(r"```(?:mermaid|mmd)\s*\n[\s\S]*?```", re.IGNORECASE)


@dataclass(frozen=True)
class ReportDiagram:
    label: str
    title: str
    mermaid: str
    reading: str
    reinforces: str

    def to_markdown(self) -> str:
        return "\n".join(
            [
                f"**{self.label} - {self.title}**",
                "",
                "```mermaid",
                self.mermaid.strip(),
                "```",
                "",
                f"Leitura: {self.reading}",
                f"Ponto reforcado: {self.reinforces}",
            ]
        )

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


def count_report_diagrams(markdown: str) -> int:
    """Count editable Mermaid diagrams already present in report markdown."""

    return len(_MERMAID_FENCE_RE.findall(markdown or ""))


def _compact_label(value: Any, fallback: str, max_chars: int = 72) -> str:
    text = re.sub(r"\s+", " ", str(value or "").strip())
    if not text:
        return fallback
    text = text.replace('"', "'").replace("[", "(").replace("]", ")")
    if len(text) > max_chars:
        text = text[: max_chars - 1].rstrip() + "..."
    return text


def build_paperbanana_report_diagrams(outline: Any | None = None) -> list[ReportDiagram]:
    """Build the mandatory editable visual pack for a final report.

    The diagrams deliberately avoid unsupported numbers and direct quotes so the
    evidence audit remains conservative. Content-specific diagrams can still be
    generated by the LLM inside sections; this pack guarantees a visual floor.
    """

    report_title = _compact_label(getattr(outline, "title", ""), "Relatorio MiroFish")
    report_summary = _compact_label(getattr(outline, "summary", ""), "Descoberta central")

    return [
        ReportDiagram(
            label="Figura A",
            title="Mapa da decisao simulada",
            mermaid=f"""
flowchart LR
  H["Hipotese testada"] --> C["Condicoes do ensaio"]
  C --> O["Observacoes da simulacao"]
  O --> L["Forca, limite e risco"]
  L --> D["Decisao recomendada"]
  T["{report_title}"] -. orienta .-> H
  S["{report_summary}"] -. sintetiza .-> D
""",
            reading="[Simulacao] O relatorio deve ser lido como passagem da hipotese testada para uma decisao condicionada por evidencias e limites.",
            reinforces="tese central, alcance da simulacao e criterio de decisao.",
        ),
        ReportDiagram(
            label="Figura B",
            title="Cadeia auditavel de evidencias",
            mermaid="""
flowchart TD
  subgraph Fontes["Fontes auditaveis"]
    TXT["Texto-base"]
    GRAFO["Grafo de entidades"]
    ACOES["Acoes dos agentes"]
  end
  TXT --> BUSCA["Ferramentas de busca"]
  GRAFO --> BUSCA
  ACOES --> BUSCA
  BUSCA --> SECOES["Secoes do relatorio"]
  SECOES --> HELENA["Analise estrategica"]
  HELENA --> AUDIT["Auditoria de citacoes e numeros"]
  AUDIT --> ENTREGA["Entrega final"]
""",
            reading="[Fato] O fluxo separa material-base, simulacao, escrita e auditoria antes da entrega.",
            reinforces="rastreabilidade, anti-alucinacao e confianca operacional.",
        ),
        ReportDiagram(
            label="Figura C",
            title="Arvore de acao e reforco",
            mermaid="""
flowchart TD
  SINAL{"Sinal observado"}
  SINAL -->|forte| EXEC["Executar recomendacao"]
  SINAL -->|parcial| REFORCO["Reforcar corpus ou rodada"]
  SINAL -->|contrario| ADV["Testar tese adversaria"]
  EXEC --> MON["Monitorar gatilhos"]
  REFORCO --> NOVA["Nova simulacao"]
  ADV --> DEC["Revisar decisao"]
  MON --> DEC
  NOVA --> DEC
""",
            reading="[Inferencia] A decisao final melhora quando o relatorio explicita o que executar, o que reforcar e o que pode virar o cenario.",
            reinforces="plano operacional, risco residual e proximos passos.",
        ),
    ]


def render_paperbanana_diagram_section(outline: Any | None = None) -> str:
    diagrams = build_paperbanana_report_diagrams(outline)
    body = "\n\n".join(diagram.to_markdown() for diagram in diagrams)
    return "\n\n".join(
        [
            f"## {DIAGRAM_SECTION_TITLE}",
            "",
            "Esta parte visual transforma o relatorio em mapas editaveis para leitura rapida e revisao posterior.",
            "",
            body,
        ]
    )


def ensure_minimum_report_diagrams(markdown: str, outline: Any | None = None) -> str:
    """Append the PaperBanana visual pack when a report has fewer diagrams."""

    content = (markdown or "").rstrip()
    if count_report_diagrams(content) >= MIN_REPORT_DIAGRAMS:
        return content + "\n"

    section = render_paperbanana_diagram_section(outline).strip()
    if not content:
        return section + "\n"
    return f"{content}\n\n---\n\n{section}\n"


def paperbanana_diagram_metadata(markdown: str) -> dict[str, Any]:
    count = count_report_diagrams(markdown)
    return {
        "schema": "mirofish.paperbanana_diagrams.v1",
        "generator": DIAGRAM_GENERATOR,
        "version": DIAGRAM_GENERATOR_VERSION,
        "minimum_required": MIN_REPORT_DIAGRAMS,
        "diagram_count": count,
        "passes_minimum": count >= MIN_REPORT_DIAGRAMS,
    }
